version: 2

models:
  - name: stg_coffee_shop__orders
    columns:
      - name: customer_id
        tests:
          - relationships:
              to: ref('stg_coffee_shop__customers')
              field: customer_id