version: 2

models:
  - name: stg_coffee_shop_monthly_orders
    columns:
      - name: customer_id
        tests:
          - relationships:
              to: ref('stg_coffee_shop_customers')
              field: id